version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: xb_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: xb_server_hub_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  glances:
    image: nicolargo/glances:latest-full
    container_name: xb_glances
    pid: host
    environment:
      - GLANCES_OPT=-w
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "61208:61208"
    restart: unless-stopped

volumes:
  postgres_data: